python3 tt.py alias -k 'org1dev' --tag 'Org:Organization 1' --tag 'Task:Development' --description 'Project work related to development either code or tooling or infrastructure implementation or configuration'
python3 tt.py alias -k 'org1infra' --tag 'Org:Organization 1' --tag 'Task:Infrastructure' --description 'Project work related to designing or planning an infrastructure'
python3 tt.py alias -k 'org1ops' --tag 'Org:Organization 1' --tag 'Task:Operations' --description 'Operations time maintaining or repairing infrastructure'
python3 tt.py alias -k 'org1arch' --tag 'Org:Organization 1' --tag 'Task:Architecture' --description 'Architectural efforts related to designing and planning systems and concepts'
python3 tt.py alias -k 'org1pm' --tag 'Org:Organization 1' --tag 'Task:Project management' --description 'Project management efforts including leading meetings setting agendas and managing project tasks and scope'
python3 tt.py alias -k 'org1scratch' --tag 'Org:Organization 1' --tag 'Task:Scratch' --description 'Time spent unallocated to a project and otherwise split across many tasks'
python3 tt.py alias -k 'org2.dev' --tag 'Org:Organization 2' --tag 'Task:Development' --description 'Project work related to development either code or tooling or infrastructure implementation or configuration'
python3 tt.py alias -k 'org2.infra' --tag 'Org:Organization 2' --tag 'Task:Infrastructure' --description 'Project work related to designing or planning an infrastructure'
python3 tt.py alias -k 'org2.ops' --tag 'Org:Organization 2' --tag 'Task:Operations' --description 'Operations time maintaining or repairing infrastructure'
python3 tt.py alias -k 'org2.arch' --tag 'Org:Organization 2' --tag 'Task:Architecture' --description 'Architectural efforts related to designing and planning systems and concepts'
python3 tt.py alias -k 'org2.pm' --tag 'Org:Organization 2' --tag 'Task:Project management' --description 'Project management efforts including leading meetings setting agendas and managing project tasks and scope'
python3 tt.py alias -k 'org2.scratch' --tag 'Org:Organization 2' --tag 'Task:Scratch' --description 'Time spent unallocated to a project and otherwise split across many tasks'
python3 tt.py alias -k 'org3.dev' --tag 'Org:Organization 3' --tag 'Task:Development' --description 'Project work related to development either code or tooling or infrastructure implementation or configuration'
python3 tt.py alias -k 'org3.infra' --tag 'Org:Organization 3' --tag 'Task:Infrastructure' --description 'Project work related to designing or planning an infrastructure'
python3 tt.py alias -k 'org3.ops' --tag 'Org:Organization 3' --tag 'Task:Operations' --description 'Operations time maintaining or repairing infrastructure'
python3 tt.py alias -k 'org3.arch' --tag 'Org:Organization 3' --tag 'Task:Architecture' --description 'Architectural efforts related to designing and planning systems and concepts'
python3 tt.py alias -k 'org3.pm' --tag 'Org:Organization 3' --tag 'Task:Project management' --description 'Project management efforts including leading meetings setting agendas and managing project tasks and scope'
python3 tt.py alias -k 'org3.scratch' --tag 'Org:Organization 3' --tag 'Task:Scratch' --description 'Time spent unallocated to a project and otherwise split across many tasks'
